import type { Metadata } from "next"

import { Inter } from "next/font/google"

import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

interface RootLayoutProps {
  children: React.ReactNode
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout(props: RootLayoutProps): React.ReactElement {
  const { children } = props
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
